# Generated by Django 6.0.1 on 2026-01-16 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userprofile_activity_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='activity_level',
            field=models.CharField(choices=[('sedentary', 'Sedentary'), ('light', 'Light'), ('moderate', 'Moderate'), ('active', 'Active'), ('very_active', 'Very Active')], default='lightly', max_length=50),
        ),
    ]
