services:
  backend:
    build:
      context: ..
      dockerfile: prod/dockerfile
    env_file:
      - ./.env.prod
    entrypoint: ["/app/prod/entrypoint.sh"]
    expose:
      - "8000"
    volumes:
      - static_data:/app/src/staticfiles
    restart: unless-stopped

  nginx:
    image: nginx
    depends_on:
      - backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/sites-enabled/myproject.conf:/etc/nginx/conf.d/myproject.conf:ro
      - static_data:/app/src/staticfiles:ro
      - certs:/etc/letsencrypt:ro
    restart: unless-stopped

  certbot:
    image: certbot/certbot:latest
    depends_on:
      - nginx
    volumes:
      - certs:/etc/letsencrypt
      - ./nginx/html:/var/www/html
    entrypoint: >
      sh -c "trap exit TERM; while :; do certbot renew --noninteractive --agree-tos; sleep 12h & wait $${!}; done"

volumes:
  static_data:
  certs:
