# Generated by Django 6.0.1 on 2026-01-16 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseNutrient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('unit', models.CharField(max_length=20)),
                ('daily_target', models.FloatField(help_text='Recommended daily intake.')),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, help_text='Ingredients, recipe, or notes.')),
                ('calories', models.PositiveIntegerField(help_text='Approximate calories per serving.')),
                ('preview_image', models.URLField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=True, help_text='If True, this meal can be randomly assigned to other users.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], max_length=20)),
            ],
            options={
                'ordering': ['date', 'meal_type'],
            },
        ),
        migrations.CreateModel(
            name='Nutrient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(help_text='Amount of this nutrient in the meal.')),
            ],
        ),
        migrations.CreateModel(
            name='UserNutrientRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_target', models.FloatField(help_text='User-specific daily intake target.')),
                ('source', models.CharField(help_text="Source of this requirement (e.g. 'user_added', 'generated').", max_length=100)),
            ],
            options={
                'verbose_name': 'User Nutrient Requirement',
                'verbose_name_plural': 'User Nutrient Requirements',
            },
        ),
        migrations.CreateModel(
            name='UserRequirementStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bmr', models.FloatField(help_text='Basal Metabolic Rate in kcal.')),
                ('tdee', models.FloatField(help_text='Total Daily Energy Expenditure in kcal.')),
                ('calories_needed', models.FloatField(help_text='Calories needed per day in kcal.')),
                ('protein_g', models.FloatField(help_text='Daily protein requirement in grams.')),
                ('protein_kcal', models.FloatField(help_text='Daily protein requirement in kcal.')),
                ('fat_g', models.FloatField(help_text='Daily fat requirement in grams.')),
                ('fat_kcal', models.FloatField(help_text='Daily fat requirement in kcal.')),
                ('carbs_g', models.FloatField(help_text='Daily carbohydrate requirement in grams.')),
                ('carbs_kcal', models.FloatField(help_text='Daily carbohydrate requirement in kcal.')),
                ('fat_factor_used', models.FloatField(help_text='Fat factor used in calculations (e.g. 0.8 for 80%).')),
            ],
        ),
    ]
