# Generated by Django 6.0.1 on 2026-01-16 05:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planner', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='creator',
            field=models.ForeignKey(help_text='The user who added this meal. Null if system-provided.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_meals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_meals', to='planner.meal'),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nutrient',
            name='base_nutrient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meal_measurements', to='planner.basenutrient'),
        ),
        migrations.AddField(
            model_name='nutrient',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrients', to='planner.meal'),
        ),
        migrations.AddField(
            model_name='usernutrientrequirement',
            name='base_nutrient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_requirements', to='planner.basenutrient'),
        ),
        migrations.AddField(
            model_name='usernutrientrequirement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrient_requirements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userrequirementstat',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='physical_stats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='mealplan',
            unique_together={('user', 'date', 'meal_type')},
        ),
        migrations.AlterUniqueTogether(
            name='nutrient',
            unique_together={('meal', 'base_nutrient')},
        ),
        migrations.AlterUniqueTogether(
            name='usernutrientrequirement',
            unique_together={('user', 'base_nutrient')},
        ),
    ]
